--- 
  apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata: 
    name: kube-pause-daemonset
  spec: 
    template: 
      metadata: 
        labels: 
          daemon: kube-pause
        name: kube-pause-ctrl
      spec: 
        containers: 
          - 
            image: akanso/kube-pause:v1
            imagePullPolicy: IfNotPresent
            name: pause-controller
            command: ["/bin/sh","-c"]
            args: ["/kube-pause-ctrl/kube-pause-ctrl --namespace=default"]
            env:
              - name: DOCKER_API_VERSION
                value: "1.35"
              - name: MY_NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            volumeMounts:
              - mountPath: /var/run/docker.sock
                name: docker-sock
                readOnly: true
            resources: 
              limits: 
                cpu: 200m
                memory: 100Mi
              requests: 
                cpu: 100m
                memory: 50Mi
        hostNetwork: true
        volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock
  
  